username_orangeHRM= "//input[@name='username']"
username_value="Admin"
password_orangeHRM = "//input[@name='password']"
password_value ="admin123"
sign_in_orangeHRM= "xpath://button[@type='submit']"
Alert_widget="CSS:#app > div > div > div:nth-child(2) > div > div:nth-child(3)"
Alert_button="CSS:div[class='element-list collapse show'] li[id='item-1'] span[class='text']"
Click_me="CSS:#alertButton"
Widgets="CSS:div:nth-child(4) div:nth-child(1) div:nth-child(1)"
Click_on_date_picker="CSS:div[class='element-list collapse show'] li[id='item-2'] span[class='text']"
Select_Date_field="CSS:#datePickerMonthYearInput"
Select_month="CSS:.react-datepicker__month-select"
Click_month="CSS:#datePickerMonthYear select option:nth-child(11)"
Click_on_year="CSS:.react-datepicker__year-select"
Select_year="CSS:#datePickerMonthYear select option:nth-of-type(94)"
alphabet_list="CSS:#demo-tabpane-list"
interaction_widget="CSS:#app > div > div > div:nth-child(2) > div > div:nth-child(5) > div > div:nth-child(3)"
click_on_sortable="xpath:/html/body/div[2]/div/div/div/div[1]/div/div/div[5]/div/ul/li[1]"
Click_grid="CSS:#demo-tab-grid"
fifth_element="CSS:#demo-tabpane-grid > div > div > div:nth-child(5)"
nineth_element="CSS:#demo-tabpane-grid > div > div > div:nth-child(9)"
click_book_store="CSS:#app > div > div > div:nth-child(2) > div > div:nth-child(6) > div > div:nth-child(3)"
username_of_user="CSS:#userName"
input_username="NamraKanwal"
pass_of_user="CSS:#password"
input_pass="testing@123"
login_button="CSS:#login"
list_of_books="xpath://*[@id='app']/div/div/div/div[2]/div[2]/div[2]/div[1]"
